### ISSUE TITLE
Allow using verification link when not logged in

### ISSUE THREAD

**Issue by ssamjh** [HangarMC/Hangar#1171]
### Observed/problematic behavior

I created an account and was told to wait for an email to verify. The email took some time to come through so I tried it later in the day after I finished work.

The URL to verify says I must be logged in, but I can't login because the account isn't verified.

I also cannot create a new account because my username already exists.

### Expected behavior

Normally, verification emails shouldn't require one to be logged in.

### Steps to reproduce

1. Make an account
2. Wait some time to click email verification
3. Attempt to click verification from another browser

**Comment by ssamjh** [comment]
Update, I was able to get in by requesting a password reset.

**Comment by MiniDigger** [comment]
decided to keep it this way, I dont want magic links, I dont want people to click on the link at all, that just trains unsecure habbits. 
the flow should be you get redirected to settings, see the prompt for verification and then copy the code you got via may there.
what I did now tho is adding a login button to the 401 error page that remembers the url you were on, so even if you logout now and press the link in the email, you can go to login and then the email will be automatically verified because of the url param, so that edge case works nicely too.
